package memcached

// This package is actually a copy of github.com/prometheus/memcached_exporter
// with only package changed from "main" to "memcached".
// This allow to import the package and use it as library

// It is generated by:
// curl https://raw.githubusercontent.com/prometheus/memcached_exporter/v0.6.0/main.go | sed 's@package main@//nolint\npackage memcached@' > memcached.go

// TODO: should the above be converted to a go generate command ?
