---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: glouton
  namespace: {{ .Values.namespace}}
  labels:
    app: glouton
spec:
  selector:
    matchLabels:
      app: glouton
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: glouton
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: glouton
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      hostPID: true
      containers:
      - image: bleemeo/glouton
        name: glouton
        ports:
        - name: http
          containerPort: 8015
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: lib-glouton
          mountPath: /var/lib/glouton
        - name: hostroot
          mountPath: /hostroot
          readOnly: true
        # We used another folder than "conf.d" because we want to merge existing
        # file from conf.d and file coming from Kubernetes glouton-config.
        - name: glouton-config
          mountPath: /etc/glouton/conf-k8s.d/
        env:
        - name: GLOUTON_CONFIG_FILES
          value: "/etc/glouton/glouton.conf,/etc/glouton/conf.d,/etc/glouton/conf-k8s.d"
        - name: GLOUTON_KUBERNETES_ENABLED
          value: "True"
        - name: GLOUTON_KUBERNETES_NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - secretRef:
            name: glouton-credentials
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: lib-glouton
        hostPath:
          path: /var/lib/glouton
      - name: hostroot
        hostPath:
          path: /
      - name: glouton-config
        configMap:
          name: glouton-config