---
apiVersion: v1
kind: Secret
metadata:
  name: glouton-credentials
  namespace: {{ .Values.namespace}}
type:
stringData:
  GLOUTON_BLEEMEO_ACCOUNT_ID: {{ .Values.bleemeo.account_id}}
  GLOUTON_BLEEMEO_REGISTRATION_KEY: {{ .Values.bleemeo.registration_key}}