// Copyright 2015-2019 Bleemeo
//
// bleemeo.com an infrastructure monitoring solution in the Cloud
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package modify

import (
	"agentgo/inputs/internal"

	"github.com/influxdata/telegraf"
)

// AddLabels adds given labels on all metric generated by given input.
//
// If an key already already exists, the value is added, followed by an "_" then the existing item value
func AddLabels(input telegraf.Input, labels map[string]string) telegraf.Input {
	if ourInput, ok := input.(*internal.Input); ok {
		ourInput.Accumulator.StaticLabels = labels
	} else {
		input = &internal.Input{
			Input: input,
			Accumulator: internal.Accumulator{
				StaticLabels: labels,
			},
		}
	}
	return input
}
