package facts

import (
	"encoding/json"
	"os"
)

// VethProvider reads the file generated by the veth script to provide a mapping
// between containers and host network interfaces.
type VethProvider struct {
	FilePath string
}

type Veth struct {
	Name        string
	ContainerID string
}

// Veths returns a mapping from containerID to interface name.
func (cp VethProvider) Veths() (map[string]string, error) {
	var veths []Veth

	jsonVeths, err := os.ReadFile(cp.FilePath)
	if err != nil {
		return nil, err
	}

	if err := json.Unmarshal(jsonVeths, &veths); err != nil {
		return nil, err
	}

	vethsByContainerID := make(map[string]string, len(veths))
	for _, veth := range veths {
		vethsByContainerID[veth.ContainerID] = veth.Name
	}

	return vethsByContainerID, nil
}
