// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"time"
)

type Label struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LabelInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type LabelsInput struct {
	Labels []*LabelInput `json:"labels"`
}

type Metric struct {
	Labels []*Label `json:"labels"`
	Points []*Point `json:"points"`
}

type Point struct {
	Time  time.Time `json:"time"`
	Value float64   `json:"value"`
}
