#!/bin/sh

getent group glouton >/dev/null || groupadd -r glouton

if ! getent passwd glouton > /dev/null; then
    useradd -r -g glouton -d /var/lib/glouton -s /sbin/nologin \
        -c "Glouton daemon" glouton
fi

# Glouton need access to Docker socket, so it need to create
# the docker group to avoid requiring to run as root.
if ! getent group docker >/dev/null; then
    groupadd -r docker
    if [ -e /var/run/docker.sock -a "`stat -c %G /var/run/docker.sock 2>/dev/null`" = "root" ]; then
        chgrp docker /var/run/docker.sock
    fi
fi

# If jmxtrans is installed, Glouton need to be able to write a jmxtrans configuration
if [ -e /var/lib/jmxtrans -a ! -e /var/lib/jmxtrans/glouton-generated.json ]; then
    if getent group jmxtrans >/dev/null; then
        echo '{"servers":[]}' > /var/lib/jmxtrans/glouton-generated.json
        chown glouton:jmxtrans /var/lib/jmxtrans/glouton-generated.json
        chmod 0640 /var/lib/jmxtrans/glouton-generated.json
    fi
fi

usermod -aG docker glouton 2> /dev/null || true

if getent group systemd-journal >/dev/null; then
    usermod -aG systemd-journal glouton 2> /dev/null || true
fi

if [ -e /var/lib/bleemeo/state.json -a ! -e /var/lib/glouton/state.json ]; then
    echo "Migrating from bleemeo-agent to Glouton"
    echo "Stopping bleemeo-agent and copying state.json from bleemeo-agent to Glouton"
    touch /var/lib/bleemeo/upgrade
    systemctl stop bleemeo-agent.service
    systemctl stop telegraf.service 2> /dev/null
    cp -a /var/lib/bleemeo/state.json /var/lib/glouton/state.json
    chown glouton:glouton /var/lib/glouton/state.json
    for filename in `ls /etc/bleemeo/agent.conf.d`; do
        if [ "$filename" = "zzz-disabled-by-glouton.conf" ]; then
            continue
        fi
        if [ "$filename" = "32-graphite_metrics_source.conf" -o "$filename" = "30-graphite_metrics_source.conf" ]; then
            continue
        fi
        if [ ! -e "/etc/glouton/conf.d/$filename" ]; then
            echo "Copy config $filename"
            cp -a "/etc/bleemeo/agent.conf.d/$filename" "/etc/glouton/conf.d/$filename"
            if [ "`stat -c %U "/etc/glouton/conf.d/$filename"`" = "bleemeo" ]; then
                chown glouton "/etc/glouton/conf.d/$filename"
            fi
            if [ "`stat -c %G "/etc/glouton/conf.d/$filename"`" = "bleemeo" ]; then
                chgrp glouton "/etc/glouton/conf.d/$filename"
            fi
        fi
    done
    # We only want to migrate /etc/bleemeo/agent.conf if it was modified.
    if [ -e /usr/bin/dpkg ]; then
        # The space after filename in the grep are important to match agent.conf and not agent.conf.d
        PACKAGE_MD5=`dpkg-query --show --showformat='${Conffiles}\n' bleemeo-agent 2>/dev/null | grep '/etc/bleemeo/agent.conf ' | awk '{print $2}'`
        CURRENT_MD5=`md5sum /etc/bleemeo/agent.conf 2> /dev/null | awk '{print $1}'`
        if [ ! -z "${PACKAGE_MD5}" -a ! -z "${CURRENT_MD5}" -a "${PACKAGE_MD5}" != "${CURRENT_MD5}" ]; then
            echo "Copy config /etc/bleemeo/agent.conf"
            cp /etc/bleemeo/agent.conf /etc/glouton/glouton.conf
        fi
    elif [ -e /usr/bin/rpm ]; then
        # rpm --verify only print line for file modified
        # the "grep 5" match line with bad md5sum
        # the if will check the result code of the last grep. If true the line was found so
        # file content (md5sum missmatch) was modified.
        if rpm --verify bleemeo-agent 2> /dev/null | grep 5 | grep --quiet /etc/bleemeo/agent.conf$; then
            echo "Copy config /etc/bleemeo/agent.conf"
            cp /etc/bleemeo/agent.conf /etc/glouton/glouton.conf
        fi
    fi
    cat > /etc/bleemeo/agent.conf.d/zzz-disabled-by-glouton.conf << EOF
        # Bleemeo agent is disabled and is replaced by Glouton.
        # If you want to rollback from Glouton to Bleemeo-agent:
        # * uninstall glouton
        # * remove this file
        # * restart bleemeo-agent
        bleemeo:
          enabled: false
        web:
          enabled: false
        telegraf:
          statsd:
            enabled: false
        influxdb:
          enabled: False
EOF
    cat > /etc/telegraf/telegraf.d/bleemeo-generated.conf << EOF
# Configuration generated by Bleemeo-agent.
# do NOT modify, it will be overwrite on next agent start.
#
# File emptied by Glouton to disable Telegraf statsd listener.
# Telegraf is no longer needed for Glouton and could be uninstalled.
EOF
fi

# Remove configuration file (Glouton's owned) and remove empty dirs related to FluentBit.
# Hide & ignore any errors.
rm -f /var/lib/glouton/fluent-bit/config/fluent-bit.conf
rmdir /var/lib/glouton/fluent-bit/config 2>/dev/null || true
rmdir /var/lib/glouton/fluent-bit/db 2>/dev/null || true
rmdir /var/lib/glouton/fluent-bit 2>/dev/null || true

chown glouton:glouton -R /var/lib/glouton

if [ -d /etc/init ]; then
   cat > /etc/init/glouton.conf <<EOF
# glouton - Monitoring agent for Bleemeo solution

description     "Glouton"

start on runlevel [2345]
stop on runlevel [!2345]

respawn
respawn limit 10 5
umask 022

setuid glouton
exec /usr/sbin/glouton

EOF
fi

if [ -e /etc/sudoers.d/glouton ]; then
   chmod 0440 /etc/sudoers.d/glouton
fi

if [ -e /etc/glouton/conf.d/30-install.conf ]; then
    chown glouton:glouton /etc/glouton/conf.d/30-install.conf
    chmod 0640 /etc/glouton/conf.d/30-install.conf
fi

# Retrive fact that needs root privilege
glouton-gather-facts 2> /dev/null
# Retrive netstat that also needs root privilege
glouton-netstat 2> /dev/null


# configure is the ordinary install and upgrade. The abort-* ones run when dpkg unwinds a
# failed upgrade or a failed remove: prerm has already stopped Glouton by then and the
# package stays installed, so the service has to be brought back up here or it stays down
# until someone notices. These four are the guard debhelper puts on the same snippets.
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || \
   [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
    # Installation or upgrade on Debian-like system
    test -e /lib/init/upstart-job && start --quiet glouton

    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload

        # A first install must not inherit deb-systemd-helper state from an installation
        # that is gone. dpkg leaves $2 unset in exactly two cases -- this machine never had
        # Glouton, or it was purged -- and both are supposed to leave no state file behind,
        # so one that survives here was left by a purge predating that cleanup. It lists an
        # enable symlink that no longer exists, which makes was-enabled report the unit as
        # disabled, so the enable and the restart below are both skipped and Glouton ends up
        # installed but never started. Purging the stale entry puts the unit back on
        # deb-systemd-helper's default path, which is to enable it.
        #
        # Deliberately not done on upgrade: $2 is set there, the state file describes the
        # installation still on the machine, and an admin's `systemctl disable glouton`
        # leaves disk state identical to this. A remove keeps the version too, so a
        # remove/reinstall cycle still honours a disable.
        if [ "$1" = "configure" ] && [ -z "$2" ] \
                && ! deb-systemd-helper --quiet was-enabled 'glouton.service'; then
            deb-systemd-helper purge 'glouton.service' >/dev/null || true
        fi

        if deb-systemd-helper --quiet was-enabled 'glouton.service'; then
            # enable creates the symlinks and records them in the state file itself.
            deb-systemd-helper enable 'glouton.service' >/dev/null || true
        else
            # The unit is disabled, so enable is skipped and nothing refreshes the state
            # file. update-state rewrites it from the current [Install] section, so purge
            # removes the symlinks this version of the unit owns rather than the ones some
            # earlier version did. It creates no symlink, so the unit stays disabled and
            # was-enabled still reports false below.
            deb-systemd-helper update-state 'glouton.service' >/dev/null || true
        fi

        if deb-systemd-helper --quiet was-enabled glouton.service; then
            deb-systemd-invoke restart glouton.service
        fi

        # The auto-upgrade timer is enabled by the get.bleemeo.com installer with a plain
        # `systemctl enable`, which records nothing in deb-systemd-helper. update-state
        # writes the state file for it, listing the symlinks the timer's [Install] section
        # owns, which is what lets postrm remove them on purge rather than leave systemd with
        # a link to a deleted unit file. Unlike enable, update-state never creates a symlink,
        # so the timer stays off wherever it is off.
        deb-systemd-helper update-state 'glouton-auto-upgrade.timer' >/dev/null || true
    fi
fi

if [ "$1" = "1" ] ; then
    # Initial installation on rpm-like system
    test -x /usr/bin/systemctl -o -x /bin/systemctl && systemctl daemon-reload
    test -x /usr/bin/systemctl -o -x /bin/systemctl && systemctl enable --quiet glouton.service
    test -x /usr/bin/systemctl -o -x /bin/systemctl && systemctl start --quiet glouton.service
fi

exit 0
