#!/bin/sh

getent group glouton >/dev/null || groupadd -r glouton

if ! getent passwd glouton > /dev/null; then
    useradd -r -g glouton -d /var/lib/glouton -s /sbin/nologin \
        -c "Glouton daemon" glouton
fi

# Glouton need access to Docker socket, so it need to create
# the docker group to avoid requiring to run as root.
if ! getent group docker >/dev/null; then
    groupadd -r docker
    if [ -e /var/run/docker.sock -a `stat -c %G /var/run/docker.sock` = "root" ]; then
        chgrp docker /var/run/docker.sock
    fi
fi

usermod -aG docker glouton 2> /dev/null || true

# TODO: should we migrate /etc/bleemeo/agent.conf ?
if [ -e /var/lib/bleemeo/state.json -a ! -e /var/lib/glouton/state.json ]; then
    echo "Migrating from bleemeo-agent to Glouton"
    echo "Stopping bleemeo-agent and copying state.json from bleemeo-agent to Glouton"
    touch /var/lib/bleemeo/upgrade
    systemctl stop bleemeo-agent.service
    systemctl stop telegraf.service
    cp -a /var/lib/bleemeo/state.json /var/lib/glouton/state.json
    chown glouton:glouton /var/lib/glouton/state.json
    for filename in `ls /etc/bleemeo/agent.conf.d`; do
        if [ "$filename" = "9999-disabled-by-glouton.conf" ]; then
            continue
        fi
        if [ ! -e "/etc/glouton/conf.d/$filename" ]; then
            echo "Copy config $filename"
            cp -a "/etc/bleemeo/agent.conf.d/$filename" "/etc/glouton/conf.d/$filename"
            if [ `stat -c %U "/etc/glouton/conf.d/$filename"` = "bleemeo" ]; then
                chown glouton "/etc/glouton/conf.d/$filename"
            fi
            if [ `stat -c %G "/etc/glouton/conf.d/$filename"` = "bleemeo" ]; then
                chgrp glouton "/etc/glouton/conf.d/$filename"
            fi
        fi
    done
    cat > /etc/bleemeo/agent.conf.d/9999-disabled-by-glouton.conf << EOF
        # Bleemeo agent is disabled and is replaced by Glouton.
        # If you want to rollback from Glouton to Bleemeo-agent:
        # * uninstall glouton
        # * remove this file
        # * restart bleemeo-agent
        bleemeo:
          enabled: false
        web:
          enabled: false
        telegraf:
          statsd:
            enabled: false
        influxdb:
          enabled: False
EOF
    cat > /etc/telegraf/telegraf.d/bleemeo-generated.conf << EOF
# Configuration generated by Bleemeo-agent.
# do NOT modify, it will be overwrite on next agent start.
#
# File emptied by Glouton to disable Telegraf statsd listener.
# Telegraf is no longer needed for Glouton and could be uninstalled.
EOF
fi


chown glouton:glouton /var/lib/glouton


if [ -e /etc/glouton/conf.d/30-install.conf ]; then
    chown glouton:glouton /etc/glouton/conf.d/30-install.conf
    chmod 0640 /etc/glouton/conf.d/30-install.conf
fi

# Retrive fact that needs root privilege
glouton-gather-facts
# Retrive netstat that also needs root privilege
glouton-netstat


if [ "$1" = "configure" ] ; then
    # Installation or upgrade on Debian-like system
    systemctl daemon-reload
    systemctl enable --quiet --now glouton.service
elif [ "$1" = "1" ] ; then
    # Initial installation on rpm-like system
    systemctl daemon-reload
    systemctl enable --quiet --now glouton.service
fi

exit 0
