#!/bin/sh
# Hook called after some package where installed/upgraded

set -e

glouton-netstat 2> /dev/null || true

if systemctl is-active --quiet glouton 2>/dev/null; then
    systemctl reload glouton
fi

if grep '^docker:' /etc/group 2> /dev/null > /dev/null; then
    if id glouton 2>/dev/null | grep -vq docker; then
        usermod -aG docker glouton

        # glouton user was added to group docker, restart agent to make new
        # permission effective.
        touch /var/lib/glouton/upgrade  # avoid disconnect/reconnect notification
        systemctl try-restart glouton restart
    fi
fi

# If jmxtrans is installed, Glouton need to be able to write a jmxtrans configuration
if [ -e /var/lib/jmxtrans -a ! -e /var/lib/jmxtrans/glouton-generated.json ]; then
    if getent group jmxtrans >/dev/null; then
        echo '{"servers":[]}' > /var/lib/jmxtrans/glouton-generated.json
        chown glouton:jmxtrans /var/lib/jmxtrans/glouton-generated.json
        chmod 0640 /var/lib/jmxtrans/glouton-generated.json
    fi
fi
