#!/bin/sh
# Hook called by a SystemD timer which will upgrade Glouton

set -e

# All our supported system have os-release file.
if [ -e /usr/lib/os-release ]; then
    . /usr/lib/os-release
    os_name=$ID
    os_version=$VERSION_ID
    os_codename=$VERSION_CODENAME
elif [ -e /etc/os-release ]; then
    . /etc/os-release
    os_name=$ID
    os_version=$VERSION_ID
    os_codename=$VERSION_CODENAME
fi

# When Glouton is gracefully shutdown, it checks for the presence of 
# this file to send the appropriate MQTT disconnect will.
AUTO_UPGRADE_FILE=/var/lib/glouton/auto_upgrade

trap "rm -f $AUTO_UPGRADE_FILE || true" EXIT

touch $AUTO_UPGRADE_FILE
chown glouton:glouton $AUTO_UPGRADE_FILE

case "$os_name" in
    ubuntu|debian)
        apt-get update || true
        export DEBIAN_FRONTEND=noninteractive
        apt-get install --assume-yes bleemeo-agent glouton
        ;;
    centos|almalinux|cloudlinux|ol|rocky|fedora|rhel)
        yum update --assumeyes bleemeo-agent glouton
        ;;
esac
