#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    purge)
        rm -f /var/lib/bleemeo/state.json
        rm -f /var/lib/bleemeo/facts.yaml
        rm -f /var/lib/bleemeo/netstat.out
        rm -f /var/lib/bleemeo/cloudimage_creation
        rm -f /etc/bleemeo/agent.conf.d/30-install.conf
        if [ -d /var/lib/bleemeo ]; then
            rmdir --ignore-fail-on-non-empty /var/lib/bleemeo
        fi
        if [ -d /etc/bleemeo/agent.conf.d ]; then
            rmdir --ignore-fail-on-non-empty /etc/bleemeo/agent.conf.d
        fi
        if [ -d /etc/bleemeo ]; then
            rmdir --ignore-fail-on-non-empty /etc/bleemeo
        fi
        deluser --quiet --system bleemeo > /dev/null || true
        ;;
esac
