#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd bleemeo > /dev/null ; then
            echo 'Adding system-user bleemeo'
            adduser --system --group --quiet --home "/var/lib/bleemeo" --no-create-home --disabled-login bleemeo

        fi
        echo 'Setting permissions for user bleemeo'
        chown bleemeo:bleemeo /var/lib/bleemeo

        if [ -e /etc/bleemeo/agent.conf.d/30-install.conf ]; then
            chown bleemeo:bleemeo /etc/bleemeo/agent.conf.d/30-install.conf
            chmod 0640 /etc/bleemeo/agent.conf.d/30-install.conf
        fi
        chown bleemeo:bleemeo /etc/

        # Retrive fact that need root privilege
        bleemeo-agent-gather-facts
        ;;
esac

#DEBHELPER#
