#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd bleemeo > /dev/null ; then
            echo 'Adding system-user bleemeo'
            adduser --system --group --quiet --home "/var/lib/bleemeo" --no-create-home --disabled-login bleemeo

        fi
        echo 'Setting permissions for user bleemeo'
        chown bleemeo:telegraf /etc/telegraf/telegraf.d/bleemeo-generated.conf
        chmod 0640 /etc/telegraf/telegraf.d/bleemeo-generated.conf
        ;;
esac

#DEBHELPER#
