#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd bleemeo > /dev/null ; then
            echo 'Adding system-user bleemeo'
            adduser --system --group --quiet --home "/var/lib/bleemeo" --no-create-home --disabled-login bleemeo

            echo 'Setting permissions for user bleemeo'
            touch /etc/collectd/collectd.conf.d/bleemeo.conf
            touch /etc/bleemeo/agent.conf.d/server.conf
            chown bleemeo /var/lib/bleemeo /var/log/bleemeo /etc/collectd/collectd.conf.d/bleemeo.conf /etc/bleemeo/agent.conf.d/server.conf
        fi
        ;;
esac

#DEBHELPER#
