#!/bin/sh

set -e

case "$1" in
    configure)
        if ! getent passwd bleemeo > /dev/null ; then
            echo 'Adding system-user bleemeo'
            adduser --system --group --quiet --home "/var/lib/bleemeo" --no-create-home --disabled-login bleemeo

        fi
        adduser --quiet telegraf docker 2> /dev/null || true
        echo 'Setting permissions for user bleemeo'
        chown bleemeo:telegraf /etc/telegraf/telegraf.d/bleemeo-generated.conf
        chmod 0640 /etc/telegraf/telegraf.d/bleemeo-generated.conf
        # Bleemeo agent modify telegraf configuration.
        if [ -x "/etc/init.d/telegraf" -o -f "/etc/init/telegraf.conf" ]; then
            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d telegraf restart || exit $?
            else
                /etc/init.d/telegraf restart || exit $?
            fi
        else
            if [ -x "`which deb-systemd-invoke 2>/dev/null`" ]; then
                deb-systemd-invoke restart telegraf.service
            else
                systemctl restart telegraf.service
            fi
        fi
        # Bleemeo agent modify its configuration.
        if [ -x "/etc/init.d/bleemeo-agent" ]; then
            touch /var/lib/bleemeo/upgrade
            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                invoke-rc.d bleemeo-agent restart || exit $?
            else
                /etc/init.d/bleemeo-agent restart || exit $?
            fi
        fi
        ;;
esac

#DEBHELPER#
