package modify

import (
	"agentgo/inputs/internal"

	"github.com/influxdata/telegraf"
)

// AddLabels adds given labels on all metric generated by given input.
//
// If an key already already exists, the value is added, followed by an "_" then the existing item value
func AddLabels(input telegraf.Input, labels map[string]string) telegraf.Input {
	if ourInput, ok := input.(*internal.Input); ok {
		ourInput.Accumulator.StaticLabels = labels
	} else {
		input = &internal.Input{
			Input: input,
			Accumulator: internal.Accumulator{
				StaticLabels: labels,
			},
		}
	}
	return input
}
