package modify

import (
	"agentgo/inputs/internal"

	"github.com/influxdata/telegraf"
)

// AddItem adds given value to item tag on all metric generated by given input.
//
// If an item tag already exists, the value is added, followed by an "_" then the existing item value
// If item tag is absent or empty, the value is added
func AddItem(input telegraf.Input, item string) telegraf.Input {
	if ourInput, ok := input.(*internal.Input); ok {
		ourInput.Accumulator.ItemValue = item
	} else {
		input = &internal.Input{
			Input: input,
			Accumulator: internal.Accumulator{
				ItemValue: item,
			},
		}
	}
	return input
}
